### ISSUE TITLE
Updated Winapp2

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#10]
@az0 I updated Winapp2. It also includes the big overhaul we did that I posted on the forums.

**Comment by ROCKNROLLKID** [comment]
@az0 I reuploaded the file and fixed 2 regressions, the one in slim cleaner you reported and another in internet explorer. I also fixed a merge issue I introduced while trying to merge it with the main file.

Please let me know if you find anything else wrong with the file.

**Comment by az0** [comment]
Yesterday I removed the committed from history because Git recorded it as 100% of the lines changing. I know it was a major change, but that seemed extreme. I would like to look into this more.

Also, have you gotten feedback from other people? Has it been pushed out to users of other applications? With some a major change it would be natural for there to be other bugs.

**Comment by ROCKNROLLKID** [comment]
Before we merged, it went through RC testing for a while. We also used our new and improved Winappdebug tool. The current file should be good to go as is and no big issues have been reported.

I also suggested Winappdebug to detect invalid lines, similar to the error you reported.
