### ISSUE TITLE
New Winapp2 pushed

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#11]
@az0 I updated Winapp2 for you. The new changes include a overhauled removed entries explained here: https://github.com/MoscaDotTo/Winapp2/commit/be9cad619e8cf7db1562e41543240e7bc63448bf Also includes updated browser section. The sections were renamed to "Firefox/Mozilla based browsers" and "Chrome/Chromium based browsers" due to the fact that we now have all the browsers on top now, rather then just chrome and Firefox. Other then that, most other changes are just more merging entries, bug fixes, and new additions.

**Comment by az0** [comment]
Thanks. I will check it out

**Comment by az0** [comment]
I checked and pushed the update

**Comment by ROCKNROLLKID** [comment]
Ah, so you grab the updates from Winapp2 respo automatically? So I do not need to push the update manually here myself?

**Comment by az0** [comment]
Yes, I have a script (that is in the repo) that grabs it, checks it, and manipulates it.  The manipulations include compression, like converting the line ends. 

I backed out your recent change to let the script do the work because I trying to log the line-by-line changes. The log summary below shows that in the Winapp-BleachBit.ini commit there were 7000-8000 changes (i.e., not every line changed--this is good), but in the Winapp2.ini commit all 19K lines changed, which I was trying to avoid. Not a big deal, though.

````
Author: Andrew Ziem 
Date:   Thu Feb 22 11:27:13 2018 -0700

    Update from upstream

 Winapp2-BleachBit.ini | 17261 ++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------
 1 file changed, 7380 insertions(+), 9881 deletions(-)

commit dce1796745c766390201cbaefa01f26e6b10a63f
Author: Andrew Ziem 
Date:   Thu Feb 22 11:20:45 2018 -0700

    Automatic update of Winapp2.ini from upstream GitHub repository

 Winapp2.ini | 38427 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------------------------
 1 file changed, 19077 insertions(+), 19350 deletions(-)

````

In the future feel free to send me a reminder (preferably as an issue ticket), but you do not need to do it.

By the way, it was a good experience today because I saw no upstream issues. I removed only one entry because it has an unsupported feature.

Thanks again
